### ISSUE TITLE
Peer Code review

### ISSUE THREAD

**Issue by Cathella** [codepantherr/to-do-list#12]
@codepantherr, congrats on completing this project. You did a great job both on the UI and functionality.
It is well structured, with good independent functions that make testing easy.

Great Job!

**Comment by codepantherr** [comment]
Thank you @Cathella 🙏

**Comment by IbrohimRasulov** [comment]
Good job! Awesome project, be proud of yourself 👏 👏 👏  I liked the hovering effect in the app, nice touch.
I can just give you some minor recommendations:
- Regarding documentation, please add a project screenshot
- For CSS, you can make icons change color when hovered
