### ISSUE TITLE
Peer-to-peer code review (2021-11-04)

### ISSUE THREAD

**Issue by AlexRS90** [codepantherr/to-do-list#9]
Hi Promise, very nice project your code is clean and easy to follow 🚀  🚀 
## Highlights
- You are using modules as expected. 
- Has a nice transition. 
- You can add a new task by clicking the list button or pressing enter button (on the keyboard). ⌨️ 
- List works as expected. 🧑‍💻 

## Suggestions
- I have only one suggestion it is to use camel case for all variables and its words, I noticed for "ToDo" you are using "todo" it could be a little confussing for some people.

I have nothing else to say than keep working like until now!!

**Comment by Fondem-Jr** [comment]
_Very nice design and easy to understand code_ 
**Keep it up**

**Comment by codepantherr** [comment]
Thank you for your feedback @AlexRS90  and @Fondem-Jr
